# FROM rhscl/httpd-24-rhel7
FROM registry.access.redhat.com/ubi8/ubi:8.0

MAINTAINER tester <test@example.com>

RUN yum install -y --disableplugin=subscription-manager httpd
RUN yum clean all --disableplugin=subscription-manager -y
RUN echo "Hello from the httpd-parent container!" > ${DOCROOT}/index.html
